### ISSUE TITLE
[BUG] MDT_APP isn't valid for position details

### ISSUE THREAD

**Issue by pgengler** [nyartcc/website#1]
### Contact Details

phil@pgengler.net

### What happened?

https://nyartcc.org/position/MDT_APP returns a "Couldnt find the callsign specified!" error. (Small nitpick: should probably be "Couldn't".) The position also doesn't show up in the "Who's online" box on the home page. It _is_ referenced from https://nyartcc.org/position/MDT_SW_APP as "Consolidates with: MDT_APP"; the link for MDT_APP is the one with the error.

### How can it be reproduced?

Go to https://nyartcc.org/position/MDT_SW_APP and click on "MDT_APP" for the  "Consolidates with: MDT_APP" section. Alternatively, go to https://nyartcc.org/position/MDT_APP directly.

### What browsers are you seeing the problem on?

Chrome

**Comment by asherrobinson** [comment]
Appears to have been resolved.
