### ISSUE TITLE
[BUG] One of the "Book Training" links still links to SetMore.

### ISSUE THREAD

**Issue by nickchen120235** [nyartcc/website#2]
### Contact Details

nickchen120235@gmail.com

### What happened?

The **Book Training** at the "Controller Actions" section to the left (PC version) / at the upper section (Mobile version) of the "Controller Panel" [(https://nyartcc.org/cp)](https://nyartcc.org/cp) still links to SetMore.

### How can it be reproduced?

Log in, click the **Book Training** in the sections mentioned above.

### What browsers are you seeing the problem on?

Microsoft Edge, Chrome, Safari, Firefox

**Comment by kmoberg** [comment]
Sorry for the late response. Thanks for the heads up, we'll fix this ASAP!

**Comment by asherrobinson** [comment]
Closed. 
ZWM-202 (GitHub Issue #2) Bugfix - Old Setmore Links #577 merged.
