### ISSUE TITLE
[BUG] Event signup time description is ambiguous

### ISSUE THREAD

**Issue by nickchen120235** [nyartcc/website#3]
### Contact Details

nickchen120235@gmail.com

### What happened?

The **date** part of the event signup modal describes the event time as
- Zulu
- NY Local Time
- Your Time

But after signing up, the **availability** part of the modal describes the time as
- Zulu
- Local (NY Local)
- Local (Your Time)

The time zones are correct, it's just the descriptions that are ambiguous.

### How can it be reproduced?

Signup to any events (in this case, the *Northeast Corridor FNO*) and check the **date** part with the **availability** part

### What browsers are you seeing the problem on?

Firefox

### Screenshots

![event-signup-screenshot](https://i.imgur.com/2xsC5Ep.png)

**Comment by asherrobinson** [comment]
Ticketed: ZWM-234

we'll clean up the labelling to make it more clear. 

Thanks for the report.

**Comment by asherrobinson** [comment]
Cleaned up, thanks again.

[ZWM-234 : Cleanup event signup date/time labelling (Github user report - issue #3)]
@[asherrobinson](https://github.com/asherrobinson) asherrobinson merged commit [043e495] into master
