### ISSUE TITLE
[BUG] Roster page cuts off top

### ISSUE THREAD

**Issue by lightbord** [nyartcc/website#5]
### Contact Details

discord: liteborder

### What happened?

It appears that the roster page is cutting off some of the controllers at the top of the list

### How can it be reproduced?

Go to the controller roster page on the website

### What browsers are you seeing the problem on?

Chrome, Firefox

### Screenshots

https://files.matthewbinkowitz.com/uploads/yvM1sn3x6I.png

**Comment by asherrobinson** [comment]
Thanks Matt. I see what you're talking about. Karl changed a bunch of formatting the other day and this looks to be an unfortunate side effect. I'll see if I can resolve. appreciate the report.

**Comment by asherrobinson** [comment]
Logged in ZWM-321
Resolved in PR 738 Merged 8/7/2023
